services:
  backend:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weather

    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local